name: CI

on:
  push:
    branches: [ "Default" ]
  pull_request:
    branches: [ "Default" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust-core

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get install -y --no-install-recommends libdbus-1-dev

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
